# This is a basic workflow to help you get started with Actions

name: Deploy DocC
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Select Xcode Version ✨
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.0.1.app/Contents/Developer
      - name: Delete DerivedData directory 🗑️
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build DocC
        run: |
          xcodebuild docbuild -scheme ScribbleLink \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO;
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/ScribbleLink.doccarchive \
            --hosting-base-path ScribbleLink \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/scribblelink\"</script>" > docs/index.html;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
